#!/bin/bash

FPDOC=~/FreePascal/fpc/bin/x86_64-linux/fpdoc

PACKAGE=lazGeoJSON

OUT=~/Programming/lazGeoJSON/docs/html
XML=~/Programming/lazGeoJSON/docs/xml
SRC=~/Programming/lazGeoJSON/src

${FPDOC} \
    --package=${PACKAGE} \
    --output=${OUT} \
    --format=html \
    --descr=${XML}/lazgeojson.xml \
    --descr=${XML}/lazgeojson.feature.xml \
    --descr=${XML}/lazgeojson.geometry.multipoint.xml \
    --descr=${XML}/lazgeojson.geometry.point.xml \
    --descr=${XML}/lazgeojson.geometry.position.xml \
    --descr=${XML}/lazgeojson.utils.xml \
    --input=${SRC}/lazGeoJSON.pas \
    --input=${SRC}/lazGeoJSON.Feature.pas \
    --input=${SRC}/lazGeoJSON.Geometry.MultiPoint.pas \
    --input=${SRC}/lazGeoJSON.Geometry.Point.pas \
    --input=${SRC}/lazGeoJSON.Geometry.Position.pas \
    --input=${SRC}/lazGeoJSON.Utils.pas \
