#!/bin/bash
/home/gcarreno/FreePascal/fpc/bin/x86_64-linux/fpdoc \
    --package=lazGeoJSON \
    --output=/home/gcarreno/Programming/lazGeoJSON/docs/html \
    --format=html \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.xml \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.feature.xml \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.geometry.multipoint.xml \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.geometry.point.xml \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.geometry.position.xml \
    --descr=/home/gcarreno/Programming/lazGeoJSON/docs/xml/lazgeojson.utils.xml \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.pas \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.Feature.pas \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.Geometry.MultiPoint.pas \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.Geometry.Point.pas \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.Geometry.Position.pas \
    --input=/home/gcarreno/Programming/lazGeoJSON/src/lazGeoJSON.Utils.pas \
